### ISSUE TITLE
[shell] not working on Windows

### ISSUE THREAD

**Issue by rolfmeesters** [pure-data/ggee#11]
```
load_object: Symbol "shell_setup" not found
 ggee/shell
... couldn't create
```

this is on Windows 10, Pd 0.52.2

**Comment by umlaeute** [comment]
32it or 64bit?

and how did you get `shell`? (self-compiled, via deken,..) which exact version?

**Comment by umlaeute** [comment]
and how did you get `shell`? (self-compiled, via deken,..) which exact version?

**Comment by umlaeute** [comment]
ah, it's actually quite simple.

the entire code in `shell.c` is protected with https://github.com/pd-externals/ggee/blob/95777602dff8ae074b7a47a9db7fecda5d94281d/control/shell.c#L4

which means, that the there is no `[shell]` for Windows.

The help-patch currently says:
> This object allows you to run commands in a UNIX shell.

which I think is supposed to imply that you need a UNIX to run `[shell]`.
the wording could be improved to explicitly state that Windows is not supported.

also, the `shell.c` probably shouldn't be compiled on Windows at all.

**Comment by umlaeute** [comment]
a cross-platform alternative for `[shell]` is [`[command]`](https://github.com/pd-externals/command/)

**Comment by rolfmeesters** [comment]
umläute schreef op 16-06-2022 15:28:

> a cross-platform alternative for [shell] is [[command](https://github.com/pd-externals/command/) 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>

Deken only gives Linux & Darwin

**Comment by umlaeute** [comment]
fair enough. but that's probably an issue to be reported at https://github.com/pd-externals/command/

in the meantime i'm not even sure whether `[command]` will work on Windows...

... actually, checking the code, it does not (having the same `#ifdef` clause as `shell`.

sorry.
