### ISSUE TITLE
[shell] not always outputting

### ISSUE THREAD

**Issue by SquidRoe** [pure-data/ggee#14]
It seems like sending [shell] a message like [date +%k%M( doesn't always send an output. 

```
[date +%k:%M(
|
[ggee/shell]
|          |
[print]    [print DONE]
```

will always give me DONE from the right outlet but not always my time from the left outlet. Tested on both Linux and Mac.

**Comment by umlaeute** [comment]
in general, i think that `[command]`(https://github.com/pd-externals/command) is a better replacement of `[shell]` (but does not work on Windows)

**Comment by SquidRoe** [comment]
Ah great, thank you - looks good on my laptop with wifi, now to drag my "portable" over to an ethernet cable...
